/* ------------------------------------------------------------------- *
 * Copyright (c) 2015, AIT Austrian Institute of Technology GmbH.      *
 * All rights reserved. See file FMITerminalBlock_LICENSE for details. *
 * ------------------------------------------------------------------- */

/**
 * @file EventLogger.h
 * @author Michael Spiegel, michael.spiegel.fl@ait.ac.at
 */

#ifndef _FMITERMINALBLOCK_TIMING_EVENT_LOGGER
#define _FMITERMINALBLOCK_TIMING_EVENT_LOGGER

#include "timing/Event.h"
#include "base/ApplicationContext.h"

#include <boost/log/sources/channel_logger.hpp>
#include <boost/log/attributes/mutable_constant.hpp>
#include <boost/log/expressions/keyword.hpp>
#include <boost/log/expressions/keyword_fwd.hpp>

#include <boost/thread/mutex.hpp>
#include <string>

namespace FMITerminalBlock 
{
	namespace Timing
	{
		using namespace FMITerminalBlock;
		using namespace boost::log;

		/** 
		 * @brief Defines the position of the logged event
		 * @details The position is defined according to the program's intended 
		 * event flow stages. In future versions the encoding of this enumeration
		 * may only be extended but not changed. It is save to use the encoding 
		 * scheme in external programs.
		 */
		enum ProcessingStage
		{
			realTimeGeneration = 0, ///< After being generated by a real-time source
			prediction = 1, ///< After predicting the event by the model
			endOfDistribution = 2, ///< After distributing the event to its sinks
			beginOfDistribution = 3, ///< Before notifying the event listeners
			locationUndefined = -1 ///< Undefined location, should be used with care
		};

		/**
		 * @brief The event logger class provides the functionality of tracing the
		 * event execution
		 * @details The class provides some facade functions which hide the boost
		 * logging framework complexity. It adds some attributes used to evaluate 
		 * the real-time behavior of the application. The class may be instantiated
		 * several times. Each event processing unit may maintain it's own instance 
		 * individually. Although it is save to use the same logger instance by more
		 * than one thread, the function may only be called by a single thread.
		 */
		class EventLogger: public sources::channel_logger_mt< ProcessingStage >
		{
		public:

			/** @brief The property's name which holds the global log file-name */
			static const std::string PROP_FILE_NAME;
			/** @brief The event time attribute's name */
			static const char* ATTR_EVENT_TIME;

			/**
			 * @brief Default C'tor
			 */
			EventLogger(void);

			/**
			 * @brief Globally adds a file sink which logs common event timing
			 * information
			 * @details <p> The sink's filename is taken from the given configuration.
			 * If it is not set or if it is set to an empty string, no sink will be 
			 * registered. The added sink will log information collected by all
			 * EventLogger instances. If the configuration is invalid, a
			 * Base::SystemConfigurationException will be thrown. </p>
			 * <p>The file will be written in a CSV-like format. Each field will be 
			 * separated by a single semicolon (;) and no header line will be written. 
			 * The fields written are:
			 * <ul>
			 *   <li>Number of the current weekday starting with Sunday = 0</li>
			 *   <li>The log record's hour. [0-23]</li>
			 *   <li>The log record's minute. [0-59]</li>
			 *   <li>The log record's second. [0.0-60.0)</li>
 			 *   <li>The logged event time-stamp. </li>
 			 *   <li>The number of the event stage. </li>
			 *   <li>Some Arbitrary debug information which may not be properly
			 *       escaped. The debug information field lasts until the next line
			 *       delimiter is reacher.</li>
			 * </ul>
			 * </p>
			 * @param context The application context used to obtain the configuration
			 * information.
			 */
			static void addEventFileSink(const Base::ApplicationContext& context);

			/**
			 * @brief Logs the given event
			 * @details It is assumed that the given event reference is valid until
			 * the function returns
			 * @param ev The reference to the recorded event
			 * @param stage The current stage of the given event
			 */
			void logEvent(Event * ev, ProcessingStage stage);

		private:
			/** @brief Mutex used to synchronize concurrent object access */
			boost::mutex objectMutex_;

			/** @brief Attribute used to log an event's time. */
			attributes::mutable_constant<fmiTime> eventTimeAttribute_;

		};

		/** @brief Defines the eventTime attribute */
		BOOST_LOG_ATTRIBUTE_KEYWORD(eventTime, EventLogger::ATTR_EVENT_TIME,fmiTime)

	}
}

#endif
